#!/usr/bin/env pybricks-micropython
"""Auto-generated by pathtracing.generate_robot for field 'unearthed'.

Pathfinding output: HOME -> mission -> HOME for each mission, avoiding
all other mission landmarks as obstacles. Edit missions.py and re-run
`python -m pathtracing.generate_robot` to regenerate.
"""

from pybricks.hubs import PrimeHub
from pybricks.parameters import Button, Color, Direction, Port, Side, Stop
from pybricks.pupdevices import Motor
from pybricks.robotics import DriveBase
from pybricks.tools import wait

DRIVEBASE_WHEEL_DIAMETER = 62.4
DRIVEBASE_AXLE_TRACK = 130

hub = PrimeHub()
ld = Motor(Port.D, positive_direction=Direction.COUNTERCLOCKWISE)
rd = Motor(Port.C, positive_direction=Direction.CLOCKWISE)
lbm = Motor(Port.F)
rbm = Motor(Port.E)

db = DriveBase(ld, rd, wheel_diameter=DRIVEBASE_WHEEL_DIAMETER, axle_track=DRIVEBASE_AXLE_TRACK)
db.use_gyro(True)

MISSIONS = []


def mission(func):
    MISSIONS.append(func)
    return func


def reset_headings():
    db.reset()
    hub.imu.reset_heading(0)
    lbm.reset_angle(0)
    rbm.reset_angle(0)


def reset_robot_state():
    db.stop()
    lbm.stop()
    rbm.stop()


@mission
def m1():
    """Heavy + Rocks (M10) (auto-pathfound)."""
    reset_headings()
    db.straight(800.1)
    db.turn(-180.0)
    db.straight(800.1)

@mission
def m2():
    """Silo (M11) (auto-pathfound)."""
    reset_headings()
    db.turn(45.0)
    db.straight(132.6)
    db.turn(-45.0)
    db.straight(571.5)
    db.turn(45.0)
    db.straight(44.2)
    db.turn(-135.0)
    db.straight(176.9)
    db.turn(-45.0)
    db.straight(571.5)

@mission
def m3():
    """Scales + Pan (M05) (auto-pathfound)."""
    reset_headings()
    db.turn(-45.0)
    db.straight(663.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(236.2)
    db.turn(135.0)
    db.straight(663.2)
    db.turn(-45.0)
    db.straight(371.2)
    db.turn(45.0)
    db.straight(44.2)

@mission
def m4():
    """Ship (M07) (auto-pathfound)."""
    reset_headings()
    db.turn(-45.0)
    db.straight(751.7)
    db.turn(45.0)
    db.straight(28.6)
    db.turn(135.0)
    db.straight(707.5)
    db.turn(45.0)
    db.straight(28.6)
    db.turn(-45.0)
    db.straight(44.2)

@mission
def m5():
    """Brush + Map (M01) (auto-pathfound)."""
    reset_headings()
    db.turn(-45.0)
    db.straight(663.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(619.0)
    db.turn(-90.0)
    db.straight(88.4)
    db.turn(-45.0)
    db.straight(28.6)
    db.turn(45.0)
    db.straight(44.2)
    db.turn(45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(176.9)
    db.turn(-45.0)
    db.straight(438.7)
    db.turn(135.0)
    db.straight(442.2)
    db.turn(-45.0)
    db.straight(67.5)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(795.9)
    db.turn(-45.0)
    db.straight(776.1)
    db.turn(45.0)
    db.straight(44.2)

@mission
def m6():
    """Minecart (M02) (auto-pathfound)."""
    reset_headings()
    db.turn(-45.0)
    db.straight(663.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(574.8)
    db.turn(-45.0)
    db.straight(202.5)
    db.turn(135.0)
    db.straight(397.9)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(795.9)
    db.turn(-45.0)
    db.straight(202.5)
    db.turn(45.0)
    db.straight(44.2)

@mission
def m7():
    """Forum + Statue (M04+M08) (auto-pathfound)."""
    reset_headings()
    db.turn(-45.0)
    db.straight(663.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(90.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(101.2)
    db.turn(45.0)
    db.straight(44.2)
    db.turn(45.0)
    db.straight(28.6)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(-45.0)
    db.straight(33.7)
    db.turn(45.0)
    db.straight(44.2)
    db.turn(-90.0)
    db.straight(44.2)
    db.turn(45.0)
    db.straight(33.7)
    db.turn(-45.0)
    db.straight(88.4)
    db.turn(45.0)
    db.straight(404.9)
    db.turn(-45.0)
    db.straight(44.2)
    db.turn(135.0)
    db.straight(663.2)
    db.turn(-45.0)
    db.straight(944.8)
    db.turn(45.0)
    db.straight(44.2)

def mission_selector():
    mission_index = 0
    if not MISSIONS:
        raise ValueError("MISSIONS is empty.")
    while True:
        hub.display.char(str(mission_index + 1))
        pressed = hub.buttons.pressed()
        if Button.LEFT in pressed:
            mission_index = (mission_index + 1) % len(MISSIONS)
            while hub.buttons.pressed():
                wait(20)
            wait(120)
            continue
        if Button.RIGHT in pressed:
            mission_index = (mission_index - 1) % len(MISSIONS)
            while hub.buttons.pressed():
                wait(20)
            wait(120)
            continue
        if Button.CENTER in pressed:
            while hub.buttons.pressed():
                wait(20)
            hub.light.on(Color.GREEN)
            try:
                MISSIONS[mission_index]()
            finally:
                reset_robot_state()
                hub.light.on(Color.BLUE)
            mission_index = (mission_index + 1) % len(MISSIONS)
            wait(250)
        wait(20)


def main():
    hub.system.set_stop_button(Button.BLUETOOTH)
    hub.display.orientation(Side.BOTTOM)
    reset_robot_state()
    hub.light.on(Color.BLUE)
    voltage = hub.battery.voltage()
    percentage = max(0, min(100, (voltage - 6000) * 100 // (8400 - 6000)))
    print("Battery: " + str(percentage) + "% (" + str(voltage) + " mV)")
    mission_selector()


main()
