"""Headless path generator.

Runs A* from HOME -> mission -> HOME for every mission in the field, with
all *other* missions marked as BARRIER discs so the robot routes around
them. Emits a pybricks-runnable robot/main.py using LebobDriveBase.

Usage:
    python -m pathtracing.generate_robot [field=unearthed] [out_path]

Defaults to writing scr/robot/main.py.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Headless pygame: no window required.
os.environ.setdefault("SDL_VIDEODRIVER", "dummy")

import pygame

from pathtracing.astar.algorithm import Algorithm
from pathtracing.astar.grid import Grid
from pathtracing.conversion.drivebase_translator import (
    commands_to_python,
    path_to_commands,
)
from pathtracing.missions import (
    GRID_HEIGHT,
    GRID_LENGTH,
    HOME_HEADING_DEG,
    HOME_POS,
    MISSION_LANDMARK_RADIUS,
    MISSIONS_BY_FIELD,
    ROBOT_RADIUS,
)

# Total inflation = robot half-width + landmark size. Keeps a 10x10 robot
# clear of every other mission model. Adjust ROBOT_SIZE in missions.py to
# scale this everywhere.
OBSTACLE_RADIUS = ROBOT_RADIUS + MISSION_LANDMARK_RADIUS

# Field-edge buffer so robot center cannot leave field. Capped at 1 below
# robot radius to avoid walling off legitimate edge-adjacent missions; the
# robot is allowed to touch the wall but not pass through it.
EDGE_BUFFER = max(1, ROBOT_RADIUS - 4)


def _build_grid(window_size):
    return Grid(
        GRID_LENGTH,
        GRID_HEIGHT,
        window_size,
        background_colour="white",
        node_transparency=255,
    )


def _apply_edge_buffer(grid: Grid):
    if EDGE_BUFFER <= 0:
        return
    for x in range(grid.length):
        for y in range(EDGE_BUFFER):
            grid[x][y].set_flag(grid[x][y].Flags.BARRIER)
            grid[x][grid.height - 1 - y].set_flag(grid[x][grid.height - 1 - y].Flags.BARRIER)
    for y in range(grid.height):
        for x in range(EDGE_BUFFER):
            grid[x][y].set_flag(grid[x][y].Flags.BARRIER)
            grid[grid.length - 1 - x][y].set_flag(grid[grid.length - 1 - x][y].Flags.BARRIER)


def _solve(grid: Grid, start, end, blocked_missions):
    """Return A* path (start -> end inclusive) or None if unreachable."""
    grid.reset_pathfinding()
    grid.clear_barriers()
    _apply_edge_buffer(grid)
    for _, _, pos in blocked_missions:
        grid.add_barrier_disc(pos[0], pos[1], OBSTACLE_RADIUS)

    # Make sure start and end are not themselves walled in by the buffer/discs.
    grid[start[0]][start[1]].set_flag(grid[start[0]][start[1]].Flags.UNCHECKED)
    grid[end[0]][end[1]].set_flag(grid[end[0]][end[1]].Flags.UNCHECKED)

    grid.set_start(*start)
    grid.set_end(*end)

    algo = Algorithm(grid, started=True)
    # Step until done. Algorithm sets started=False when finished/exhausted.
    while algo.started:
        algo.step()
    if not algo.found_path:
        return None
    # algo.path is end -> ... -> first-after-start. Reverse and prepend start.
    return [start] + list(reversed(algo.path))


def generate(field: str = "unearthed", out_path: Path | None = None) -> Path:
    pygame.init()
    pygame.display.set_mode((1, 1))  # dummy driver still needs init for Surface

    grid = _build_grid((1500, 866))
    missions = MISSIONS_BY_FIELD[field]
    if not missions:
        raise SystemExit(f"No mission positions defined for field '{field}'")

    mission_blocks: list[tuple[str, str, list[tuple[str, float]]]] = []
    failures: list[str] = []

    for i, (mid, name, target) in enumerate(missions):
        others = [m for j, m in enumerate(missions) if j != i]

        out_path_cells = _solve(grid, HOME_POS, target, others)
        if out_path_cells is None:
            failures.append(f"{mid} {name} (HOME -> target)")
            continue
        return_path_cells = _solve(grid, target, HOME_POS, others)
        if return_path_cells is None:
            failures.append(f"{mid} {name} (target -> HOME)")
            continue

        out_cmds = list(path_to_commands(out_path_cells, HOME_HEADING_DEG))
        # On return, robot ends facing target with last heading from outward leg;
        # but mission code typically resets headings, so start return from 0 too.
        return_cmds = list(path_to_commands(return_path_cells, HOME_HEADING_DEG))

        mission_blocks.append((mid, name, out_cmds + return_cmds))

    if failures:
        print("WARNING: unreachable missions:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)

    code = _render_robot_module(field, mission_blocks)
    out_path = out_path or Path("scr") / "robot" / "main.py"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(code)
    print(f"wrote {out_path} ({len(mission_blocks)} missions)")
    return out_path


def _render_robot_module(field: str, blocks) -> str:
    header = f'''#!/usr/bin/env pybricks-micropython
"""Auto-generated by pathtracing.generate_robot for field '{field}'.

Pathfinding output: HOME -> mission -> HOME for each mission, avoiding
all other mission landmarks as obstacles. Edit missions.py and re-run
`python -m pathtracing.generate_robot` to regenerate.
"""

from pybricks.hubs import PrimeHub
from pybricks.parameters import Button, Color, Direction, Port, Side, Stop
from pybricks.pupdevices import Motor
from pybricks.robotics import DriveBase
from pybricks.tools import wait

DRIVEBASE_WHEEL_DIAMETER = 62.4
DRIVEBASE_AXLE_TRACK = 130

hub = PrimeHub()
ld = Motor(Port.D, positive_direction=Direction.COUNTERCLOCKWISE)
rd = Motor(Port.C, positive_direction=Direction.CLOCKWISE)
lbm = Motor(Port.F)
rbm = Motor(Port.E)

db = DriveBase(ld, rd, wheel_diameter=DRIVEBASE_WHEEL_DIAMETER, axle_track=DRIVEBASE_AXLE_TRACK)
db.use_gyro(True)

MISSIONS = []


def mission(func):
    MISSIONS.append(func)
    return func


def reset_headings():
    db.reset()
    hub.imu.reset_heading(0)
    lbm.reset_angle(0)
    rbm.reset_angle(0)


def reset_robot_state():
    db.stop()
    lbm.stop()
    rbm.stop()


'''
    body_parts = []
    for mid, name, cmds in blocks:
        body_parts.append(f"@mission\ndef {mid}():\n    \"\"\"{name} (auto-pathfound).\"\"\"\n    reset_headings()\n{commands_to_python(cmds)}\n\n")

    footer = '''def mission_selector():
    mission_index = 0
    if not MISSIONS:
        raise ValueError("MISSIONS is empty.")
    while True:
        hub.display.char(str(mission_index + 1))
        pressed = hub.buttons.pressed()
        if Button.LEFT in pressed:
            mission_index = (mission_index + 1) % len(MISSIONS)
            while hub.buttons.pressed():
                wait(20)
            wait(120)
            continue
        if Button.RIGHT in pressed:
            mission_index = (mission_index - 1) % len(MISSIONS)
            while hub.buttons.pressed():
                wait(20)
            wait(120)
            continue
        if Button.CENTER in pressed:
            while hub.buttons.pressed():
                wait(20)
            hub.light.on(Color.GREEN)
            try:
                MISSIONS[mission_index]()
            finally:
                reset_robot_state()
                hub.light.on(Color.BLUE)
            mission_index = (mission_index + 1) % len(MISSIONS)
            wait(250)
        wait(20)


def main():
    hub.system.set_stop_button(Button.BLUETOOTH)
    hub.display.orientation(Side.BOTTOM)
    reset_robot_state()
    hub.light.on(Color.BLUE)
    voltage = hub.battery.voltage()
    percentage = max(0, min(100, (voltage - 6000) * 100 // (8400 - 6000)))
    print("Battery: " + str(percentage) + "% (" + str(voltage) + " mV)")
    mission_selector()


main()
'''
    return header + "".join(body_parts) + footer


if __name__ == "__main__":
    args = sys.argv[1:]
    field = args[0] if args else "unearthed"
    out = Path(args[1]) if len(args) > 1 else None
    generate(field, out)
